### ISSUE TITLE
[상우] 1926 그림 코드 리뷰

### ISSUE THREAD

**Issue by khyun3** [LeeA0/AlgorithmNote#1]
### 1.
https://github.com/LeeA0/AlgorithmNote/blob/e21c4bcf959ed514939c356a44a3e55eb392d10d/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/SW_1926_%EA%B7%B8%EB%A6%BC.java#L14
```
Integer.MIN_VALUE == -2,147,483,648 입니다.
```
여기서 minValue로 초기화하는 이유가 있을까요? 
<br><br>
### 2.
https://github.com/LeeA0/AlgorithmNote/blob/e21c4bcf959ed514939c356a44a3e55eb392d10d/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/SW_1926_%EA%B7%B8%EB%A6%BC.java#L47

여기 부분도 불필요한 코드가 들어가는 거 같습니다.
max변수는 static으로 선언하셨는데 
기본적으로 0이므로 `Integer.MIN_VALUE`로 초기화할 필요가 없다고 생각합니다.
<br><br>
### 3.
https://github.com/LeeA0/AlgorithmNote/blob/e21c4bcf959ed514939c356a44a3e55eb392d10d/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/SW_1926_%EA%B7%B8%EB%A6%BC.java#L68

`cr`, `cc`를 만드는 이유는 무엇인가요? `curr`로 이용가능하지 않을까요!?
<br><br>

https://github.com/LeeA0/AlgorithmNote/blob/e21c4bcf959ed514939c356a44a3e55eb392d10d/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/SW_1926_%EA%B7%B8%EB%A6%BC.java#L74

`visited`배열을 만든 이유는 무엇인가요?
`map`으로 모두 처리가 가능할 것 같습니다.
<br><br>
### 4.
https://github.com/LeeA0/AlgorithmNote/blob/e21c4bcf959ed514939c356a44a3e55eb392d10d/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/SW_1926_%EA%B7%B8%EB%A6%BC.java#L80
여기서 반복마다 `max`값을 갱신하고 있는데 
`41Line`바로 아래에서 각 그림마다 1번만 비교하는 방법이 더 효율적이지 않을까요?

**Comment by upswp** [comment]
1. 최대 그림 갯수를 파악하기위해 max에 MIN_VALUE를 이용하여 값을 비교했습니다.
2. 비교를 MIN_VALUE를 기준으로 진행을 해서 확인하는 과정이 필요한 부분은 맞습니다. 불필요하기보다 기준점이 달랐다 봅니다.
3. curr의 배열값을 가져와서 다음에 한번 짜볼게요!
4. 말씀하신것처럼 4방탐색마다 진행하기보다 확실히 41번째 위치가 좋겠네요! 다음에 참고하겠습니다 감사합니다.

**Comment by devtitch** [comment]
max를 MIN_VALUE가 아니라 0으로 초기화 한다면 그림이 안주어졌을 때의 예외 사항을 따로 체크하지 않아도 될것 같아요.

**Comment by upswp** [comment]
max 값에 MIN_VALUE를 습관적으로 진행한거 같네요! 다음에 적용해보겠습니다 감사합니다 !
