### ISSUE TITLE
[수빈]Scanner vs bufferedReader

### ISSUE THREAD

**Issue by khyun3** [LeeA0/AlgorithmNote#10]
https://github.com/LeeA0/AlgorithmNote/blob/9e9db7528e662aeab80e6f089d90441252abde6d/sort/BOj_10814_%EB%82%98%EC%9D%B4%EC%88%9C%EC%A0%95%EB%A0%AC/SB_10814_%EB%82%98%EC%9D%B4%EC%88%9C%EC%A0%95%EB%A0%AC.java#L25

### Scanner vs bufferedReader
|특징|scanner|bufferedReader|
|---|---|---|
|버퍼 사이즈|1,024byte |8,192byte |
|데이터 파싱|YES|NO(only String)|
|I/O Exception| NO | YES |
| thread safe | NO | YES |
| 속도 | 느림 | 빠름 |

버퍼 사이즈 + 데이터 파싱(int형, double 등등)을 하지 않기 때문에 bufferedReader가 더 빠르다고 함
나이는 bufferedReader가 더 많음  자바 1.1부터 있었다고 함
Scanner 는 자바 1.5에 추가 됨

그냥 공부할겸 써봤습니당ㅋㅋㅋㅋ

**Comment by devtitch** [comment]
수업때부터 익히 들어 알고 있지만,,,,ㅋㅋㅋbufferedReader를 사용하면 Scanner보다 2배는 더 귀찮다고 느껴서 사용합니다
+)삼성 역테를 제외한 대부분의 코테는 입력부터 받을 필요가 없찌!!
