### ISSUE TITLE
[수빈][상우]arrayList vs LinkedList

### ISSUE THREAD

**Issue by khyun3** [LeeA0/AlgorithmNote#12]
https://github.com/LeeA0/AlgorithmNote/blob/9e9db7528e662aeab80e6f089d90441252abde6d/sort/BOj_10814_%EB%82%98%EC%9D%B4%EC%88%9C%EC%A0%95%EB%A0%AC/SB_10814_%EB%82%98%EC%9D%B4%EC%88%9C%EC%A0%95%EB%A0%AC.java#L36

https://github.com/LeeA0/AlgorithmNote/blob/9e9db7528e662aeab80e6f089d90441252abde6d/sort/BOJ_10825_%EA%B5%AD%EC%98%81%EC%88%98/SW_10825_%EA%B5%AD%EC%98%81%EC%88%98.java#L43

PriorityQueue가 가장 빠른거 같아요.
한 번 사용해 봅시댜.
아영님과 함께 3가지 형태로 정렬하고 비교 해봤습니다.
* ArrayList
* LinkedList
* PriorityQueue 

테스트 해보세요!

참고로 알아두면 좋은 것
ArrayList vs LinkedList
|Algorithm | ArrayList | LinkedList |
|-----------|-----------|-----------|
|seek front        |    O(1)    |     O(1)|
|seek back         |    O(1)    |     O(1)|
|seek to index    |     O(1)   |      O(N)|
|insert at front    |   O(N)    |     O(1)|
|insert at back     |   O(1)     |    O(1)|
|insert after an item | O(N)  |       O(1)|

![image](https://user-images.githubusercontent.com/9759988/107125566-193f0e00-68ee-11eb-8dd7-1718e77bdcdc.png)

>추가 1 )
> 클래스에서 `Comparable` implements 받는게 `lambda`보다 빨랐습니다.

>추가 2) 
>https://stackoverflow.com/questions/322715/when-to-use-linkedlist-over-arraylist-in-java

**Comment by upswp** [comment]
수정 진행해서 코드에 반영해보겠습니다.

**Comment by devtitch** [comment]
넹~다음부터 자료구조 선택할때 유의해서 해볼게요ㅎ
