### ISSUE TITLE
[상우] 불필요한 코드 & 주석의 의미를 잘 모르겠습니다.

### ISSUE THREAD

**Issue by khyun3** [LeeA0/AlgorithmNote#13]
### 불필요한 코드
https://github.com/LeeA0/AlgorithmNote/blob/9e9db7528e662aeab80e6f089d90441252abde6d/sort/BOJ_1377_%EB%B2%84%EB%B8%94%EC%86%8C%ED%8A%B8/SW_1377_%EB%B2%84%EB%B8%94%EC%86%8C%ED%8A%B8.java#L38

https://github.com/LeeA0/AlgorithmNote/blob/9e9db7528e662aeab80e6f089d90441252abde6d/sort/BOJ_1377_%EB%B2%84%EB%B8%94%EC%86%8C%ED%8A%B8/SW_1377_%EB%B2%84%EB%B8%94%EC%86%8C%ED%8A%B8.java#L48

https://github.com/LeeA0/AlgorithmNote/blob/9e9db7528e662aeab80e6f089d90441252abde6d/sort/BOJ_1377_%EB%B2%84%EB%B8%94%EC%86%8C%ED%8A%B8/SW_1377_%EB%B2%84%EB%B8%94%EC%86%8C%ED%8A%B8.java#L53

https://github.com/LeeA0/AlgorithmNote/blob/9e9db7528e662aeab80e6f089d90441252abde6d/sort/BOJ_1377_%EB%B2%84%EB%B8%94%EC%86%8C%ED%8A%B8/SW_1377_%EB%B2%84%EB%B8%94%EC%86%8C%ED%8A%B8.java#L56
* max값만 출력하면 되므로 stringbuilder 사용이 필요 없을 것 같습니다.
* count는 pq를 n번 만큼 for문으로 poll 시키면 정확하게 pq에 들어있는 수 만큼 반복하므로 더 보기 편하게 바꿀 수 있을 것 같습니다.
<br><br>

### 의미 파악이 잘 안된 주석

https://github.com/LeeA0/AlgorithmNote/blob/9e9db7528e662aeab80e6f089d90441252abde6d/sort/BOJ_1377_%EB%B2%84%EB%B8%94%EC%86%8C%ED%8A%B8/SW_1377_%EB%B2%84%EB%B8%94%EC%86%8C%ED%8A%B8.java#L55

해당 부분 주석이 어떤 의미 인가유?

**Comment by upswp** [comment]
필요 없을 것 같은 이유를 설명 부탁드립니다.

**Comment by khyun3** [comment]
변경 내용 확인부탁드려용

**Comment by upswp** [comment]
적용해서 다시 한번 풀어보겠습니다! 감사합니다!
