### ISSUE TITLE
[상우] 입력데이터에 대한 리뷰

### ISSUE THREAD

**Issue by khyun3** [LeeA0/AlgorithmNote#14]
https://github.com/LeeA0/AlgorithmNote/blob/9e9db7528e662aeab80e6f089d90441252abde6d/sort/BOJ_10825_%EA%B5%AD%EC%98%81%EC%88%98/SW_10825_%EA%B5%AD%EC%98%81%EC%88%98.java#L12

String으로 모든 데이터를 받아오는 이유가 궁금합니다.

https://github.com/LeeA0/AlgorithmNote/blob/9e9db7528e662aeab80e6f089d90441252abde6d/sort/BOJ_10825_%EA%B5%AD%EC%98%81%EC%88%98/SW_10825_%EA%B5%AD%EC%98%81%EC%88%98.java#L46

데이터 받을 때, 자료형 맞게 잘 받아오면
Integer.parseInt안하고 가능할 것 같습니다.

**Comment by upswp** [comment]
한번에 비교를 하기 위해서 입력을 하나의 형태의 String으로 받아서 진행했습니다.
이후 Integer에 해당하는 점수끼리 비교를 진행하였고 
입력받은 이름 비교 이후 점수 순으로 비교를 진행했습니다.
데이터를 받을때 자료형에 맞게 잘 받아오면 물론 parsing을 안한 상태로 진행이 가능하겠지만
코드 refactoring 과정에서 수정하였습니다.
말씀 하신 부분처럼 integer.parserInt를 진행 하는 부분에서 단점이 있을까요?

**Comment by khyun3** [comment]
Scanner의 경우는 자료형 파싱 + 버퍼의 크기 때문에 bufferedReader보다 속도가 느립니다.
(Scanner의 파싱이 Integer.parseInt 같이 따로 파싱하는 것 보다는 느리다고 합니다)
여기서 유추할 수 있는 건 데이터를 파싱하는 시간이 생각보다 영향을 많이 준다는 것입니다.

처음 데이터를 받을 때, 한 번만 파싱 해두면 compare시 따로 파싱을 하지 않아도 되므로 
속도 측면에서 유리할 것이라고 생각합니다.

**Comment by upswp** [comment]
파싱하는 부분을 고려해서 다시한번 소스 코드 속도 부분에서 테스트 해보겠습니다. 조언 감사합니다!
