### ISSUE TITLE
[범석] 10814 나이순정렬 코드리뷰

### ISSUE THREAD

**Issue by LeeA0** [LeeA0/AlgorithmNote#15]
https://github.com/LeeA0/AlgorithmNote/blob/68c16dc8bc9bdec4d1547ba19a60f089b4de43b7/sort/BOj_10814_%EB%82%98%EC%9D%B4%EC%88%9C%EC%A0%95%EB%A0%AC/BS_10814_%EB%82%98%EC%9D%B4%EC%88%9C%EC%A0%95%EB%A0%AC.java#L45
문자열을 +를 하게되면 공간적으로도 시간적으로도 낭비라고 알고 있습니다.
예를 들어 a+b+c를 하게되면 a, b, c, ab, abc가 전부 생기게됩니다.
특히 이런 단순한 문제인 경우 출력횟수가 많은데, 이런 경우 Stringbuilder를 사용하는 것이 더 유용할 것이라 생각됩니다!

**Comment by callipenguin** [comment]
StringBuilder 쓰는게 손에 익지 않아서 무심코 println을 남발하곤 하는데 지적 감사합니다!
국영수 문제만해도 시간이 너무 많이 절약되어서 StringBuilder의 힘을 실감했습니다 ㅎㅎ
