### ISSUE TITLE
[수빈] 1926 그림 코드 리뷰

### ISSUE THREAD

**Issue by upswp** [LeeA0/AlgorithmNote#2]
https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/SB_1926_%EA%B7%B8%EB%A6%BC_bfs.java#L18

static 처리를 하여 Queue를 처리한 이유가 있을까요?

**Comment by devtitch** [comment]
bfs() 안에 que를 선언해도 되지만 알고리즘 문제풀이에서는 GC를 
크게 신경쓰지 않아도 될 것 같아서 습관적으로 static으로 선언했습니다.
