### ISSUE TITLE
[기현] 1926 그림 코드리뷰

### ISSUE THREAD

**Issue by upswp** [LeeA0/AlgorithmNote#3]
https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/KH_1926_%EA%B7%B8%EB%A6%BC.java#L46

https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/KH_1926_%EA%B7%B8%EB%A6%BC.java#L61

bfs로 돌렸을때랑 dfs로 돌렸을때랑 차이가 어떤게 있었나요?

**Comment by khyun3** [comment]
BFS로 해당 문제를 풀었을 때 메모리, 수행 시간은 아래와 같습니다.
![image](https://user-images.githubusercontent.com/9759988/105622939-e1998600-5e58-11eb-903c-089b2b63471d.png)

DFS로 해당 문제를 풀었을 때 메모리, 수행 시간은 아래와 같습니다.
![image](https://user-images.githubusercontent.com/9759988/105622952-13aae800-5e59-11eb-9f50-7413cd655ac7.png)

DFS는 재귀형태로 수행됩니다. 따라서  함수 호출의 overhead가 스텍에 쌓이게 되고 이 떄문에 메모리를 많이 차지합니다.
반면 BFS는 que에 쌓이는 컬랙션 객체나 class 객체의 크기가 크지 않다면 훨씬 적은 overhead를 가지기 떄문에
메모리 측면으로는 유리할 수 있습니다.

시간 복잡도 측면에서 보자면 
BFS, DFS 모두 아래와 같이 시간 복잡도를 가집니다.
인접행렬로 풀었을 때 : `O(N^2)`
인접리스트로 풀었을 때 : `O(V+E)`

따라서 문제의 특성에 따라 BFS, DFS를 잘 선택하여 풀거나 
1926번 같이 BFS, DFS 모두 사용이 가능한 문제는 공간 복잡도 측면에서 BFS가 유리할 수 있습니다.
