### ISSUE TITLE
[아영] 2606 바이러스 코드 리뷰

### ISSUE THREAD

**Issue by upswp** [LeeA0/AlgorithmNote#4]
https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_2606_%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4/AY_2606_%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4_using_bfs.java#L16

- trim() 처리를 한 이유가 있을까요?

https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_2606_%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4/AY_2606_%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4_using_bfs.java#L27
https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_2606_%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4/AY_2606_%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4_using_bfs.java#L28

- 위의 두 라인 설명 부탁드립니다!

https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_2606_%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4/AY_2606_%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4_using_bfs.java#L42

- 위의 for문 구문 설명 부탁드립니다!

**Comment by LeeA0** [comment]
1. 혹시 모를 입력값의 좌우 공백 처리를 위해 사용했습니다.
2. 바이러스 문제의 그래프의 경우 양방향성이기 때문에 a에서 b로 b에서 a로 이동할 수 있다는 것을 표현했습니다.
3. 현재 위치의 점에서 갈 수 있는 점을 방문하기위해 for문을 넣었습니다.
