### ISSUE TITLE
[기현] 1260 DFS와BFS 코드 리뷰

### ISSUE THREAD

**Issue by upswp** [LeeA0/AlgorithmNote#5]
https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_1260_BFSDFS/KH_1260_BFSDFS.java#L25

```
The expression of type LinkedList[] needs unchecked conversion to conform to LinkedList<Integer>[]
```
경고가 발생할텐데 해결할 수 있는 방법이 있을까요?

https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_1260_BFSDFS/KH_1260_BFSDFS.java#L54

- 메서드에서 throws Exception처리를 하는건 처음봤는데 혹시 어떤 의미로 사용이 되었나요?

**Comment by khyun3** [comment]
### 1
원래 List형태를 배열로 만드는 것은 안전하지 못한 방법이라고 합니다.
하지만 problem solving에서는 효율적으로 문제를 풀기위해 사용합니다.
해당 warning을 해결하기 위해서는 다음과 같이 `어노테이션`을 활용할 수 있습니다.
```
@SuppressWarnings({"unchecked"})
LinkedList<Integer>[] tableX = new LinkedList[10];
```
또 다른 방법으로 List를 2차원 형태로 만드는 방법이 있습니다.
```
ArrayList< LinkedList<T>>
```

https://stackoverflow.com/questions/14280570/type-safety-warning-when-i-put-a-linkedlist-inside-an-array

<br><br>

### 2
해당 부분에 **throws Exception**이 걸려있는 이유는 아래 2가지 출력 방법 중 **BufferedWriter** 때문입니다.
```
bufferedWriter
StringBuilder
```
**bufferedWriter**는 **bufferedReader**와 동일하게 **IOException**으로 **throws**하거나 **try-catch**문을 작성해야합니다.
이 문제는 **StringBuilder**로 출력하는게 더 빨랐고 **bufferedWriter를** 지우면서 **throws Exception**을 삭제하지 않았습니다.
지적 감사합니다~!
