### ISSUE TITLE
[기현] 1926 그림 코드리뷰

### ISSUE THREAD

**Issue by LeeA0** [LeeA0/AlgorithmNote#6]
https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/KH_1926_%EA%B7%B8%EB%A6%BC.java#L27

1. `map[i][j] = Integer.parseInt(st.nextToken())==1` 이렇게 작성하시면 코드가 간결해줘서 더욱 좋을 것같습니다 ^_^

https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/KH_1926_%EA%B7%B8%EB%A6%BC.java#L88

2.  `return (nr>=0 && nr<N && nc>=0 && nc<M)` 이렇게 작성하시면 코드가 간결해줘서 더욱 좋을 것같습니다 ^_^

**Comment by khyun3** [comment]
1. 오호 감사합니다.
2. 오호.. 아영님 초고수시군요?
