### ISSUE TITLE
[수빈] 1260 DFS BFS 코드 리뷰

### ISSUE THREAD

**Issue by khyun3** [LeeA0/AlgorithmNote#7]
https://github.com/LeeA0/AlgorithmNote/blob/fad3e29599a333c122fe765c5b8b0990950554b0/BFS_DFS/BOJ_1260_BFSDFS/SB_1260_DFS%EC%99%80BFS.java#L22

hoxy 인접행렬을 사용한 이유가 있나요?
**인접리스트**도 사용해보면 좋을거 같습니다.

**Comment by devtitch** [comment]
구현이 쉬워서 인접행렬을 사용하였는데
인접 리스트로도 한번 풀어볼겠습니다~
