### ISSUE TITLE
[상우] 1926 그림 코드 리뷰

### ISSUE THREAD

**Issue by LeeA0** [LeeA0/AlgorithmNote#8]
https://github.com/LeeA0/AlgorithmNote/blob/a3d8f611f88874b0465b13bb10e1f8b0b6bf2308/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/SW_1926_%EA%B7%B8%EB%A6%BC.java#L59

1. 주석의 의미가 모호한 것같습니다. 사용하신 용도로는 한 그림의 넓이를 세는데 사용하신 것같은데, 자세하게 설명해주실 수 있으시겠습니까?

https://github.com/LeeA0/AlgorithmNote/blob/a3d8f611f88874b0465b13bb10e1f8b0b6bf2308/BFS_DFS/BOJ_1926_%EA%B7%B8%EB%A6%BC/SW_1926_%EA%B7%B8%EB%A6%BC.java#L86

2.  `return (r >= 0 && r < n && c >= 0 && c < m)`을 사용 하시면 코드가 더욱 간결해질 것 같습니다 ^_^

**Comment by upswp** [comment]
### 1. 주석의 의미가 모호한 것같습니다. 사용하신 용도로는 한 그림의 넓이를 세는데 사용하신 것같은데, 자세하게 설명해주실 수 있으시겠습니까?
```

public static void bfs(int r, int c, int cnt, int countMAX) {
		Queue<int[]> que = new LinkedList<int[]>();
		que.offer(new int[] {r,c});
		visited[r][c]=cnt;
		
		while(!que.isEmpty()) {
			int[] curr = que.poll();
			int cr = curr[0];
			int cc = curr[1];
			for (int d = 0; d < 4; d++) {
				int nr = cr +dr[d];
				int nc = cc +dc[d];
				if (!check(nr,nc)) continue;
				if (map[nr][nc]==1 && visited[nr][nc] == 0) {
					countMAX++;
					visited[nr][nc]=cnt;
					que.offer(new int[] {nr,nc});
				}
				// 가장 넓은 그림일 경우 max값 최신화
				if (max<countMAX)  max = countMAX;
			}
		}
	}
```

- 해당 부분은 전체 그림의 갯수를 파악하는 cnt와 가장 넓은 그림의 크기를 찾는 countMAX Param입니다.
- 본 소스 75번째 줄에서 countMAX 부분을 ++ 상태로 진행하여 값을 더합니다. 이후 max 값과 비교하여 max값을 최신화 하는 위치는 80번째 라인입니다. 

### 2. 
해당 이슈에 있어서 다음 범위 지정하는 부분에서 적용시켜보겠습니다. 감사합니다.

**Comment by LeeA0** [comment]
설명해주신 것으로 보아 countMAX라는 변수는 한덩어리 그림의 총 넓이라는 의미로 받아들여지는데, 작성하신 '가장 넓은 그림의 넓이'는 max의 설명에 더 가까우신 것 같습니다.

**Comment by upswp** [comment]
max값을 카운트 하기위해 countMAX라 사용하였고 각 그림의 크기를 파악했습니다.
